let g:sync_list =
\ [
    \ {'args': {'-avP': '', '--exclude': '.*.swp'}, 'local_path': '/Users/bytedance/Documents/code/python/toutiao_relativity_tasks/tasks/classification/', 'remote_user': '18223.liangjiahao-24.ws', 'remote_host': 'ssh-candy-lq.workspace.byted.org', 'remote_path': '/mlx_devbox/users/liangjiahao.24/repo/toutiao_relativity_tasks/tasks/classification/'},
    \ {'args': {'-avP': '', '--exclude': '.*.swp'}, 'local_path': '/Users/bytedance/Documents/code/python/multimodal_unified_classfication/', 'remote_user': '10607.liangjiahao-24.ws', 'remote_host': 'ssh-candy-lq.workspace.byted.org', 'remote_path': '/mlx_devbox/users/liangjiahao.24/repo/multimodal_unified_classfication/'},
    \ {'args': {'-avP': '', '--exclude': '.*.swp'}, 'local_path': '/Users/bytedance/Documents/code/python/tt_multi_modal/', 'remote_user': '10607.liangjiahao-24.ws', 'remote_host': 'ssh-candy-lq.workspace.byted.org', 'remote_path': '/mlx_devbox/users/liangjiahao.24/repo/tt_multi_modal/'},
    \ {'args': {'-avP': '', '--exclude': '.*.swp'}, 'local_path': '/Users/bytedance/Documents/code/python/relativity_data/', 'remote_user': 'liangjiahao.24', 'remote_host': '10.148.51.206', 'remote_path': '/data01/home/liangjiahao.24/relativity_data/'},
\ ]
    " \ {'args': {'-avP': '', '--exclude': '.*.swp'}, 'local_path': '/Users/bytedance/Documents/code/python/toutiao_relativity_tasks/tasks/classification/', 'remote_user': '10607.liangjiahao-24.ws', 'remote_host': 'ssh-candy-lq.workspace.byted.org', 'remote_path': '/mlx_devbox/users/liangjiahao.24/repo/toutiao_relativity_tasks/tasks/classification/'},
"   \ {'args': {'-avP': '', '--exclude': '.*.swp'}, 'local_path': '/Users/ljh/Documents/code/python/DeepFake_rPPG/code/', 'remote_user': 'pris', 'remote_host': '10.112.209.228', 'remote_path': '/home/ljh/Documents/code/python/DeepFake_rPPG/code/'},
"   \ {'args': {'-avP': '', '--exclude': '.*.swp'}, 'local_path': '/Users/ljh/Documents/code/python/PFA_BUPT/pfa/', 'remote_user': 'ljh', 'remote_host': '10.112.71.173', 'remote_path': '~/Documents/code/python/PFA/pfa/'},
"   \ {'args': {'-avP': '', '--exclude': '.*.swp'}, 'local_path': '/Users/goodlplus/Documents/code/python/rPPG/', 'remote_user': 'pris', 'remote_host': '10.112.66.58', 'remote_path': '/home/ljh/Documents/code/python/rPPG/'},
"   \ {'args': {'-avP': '', '--exclude': '.*.swp'}, 'local_path': '/Users/goodlplus/Documents/code/python/DeepFake_rPPG/', 'remote_user': 'ljh', 'remote_host': '10.112.71.173', 'remote_path': '/home/ljh/Documents/code/python/DeepFake_rPPG/code/'},
"   \ {'args': {'-avP': '', '--exclude': '.*.swp'}, 'local_path': '/Users/goodlplus/Documents/code/python/DeepFake_rPPG/', 'remote_user': 'pris', 'remote_host': '10.112.209.228', 'remote_path': '/home/ljh/Documents/code/python/DeepFake_rPPG/code/'},
"   \ {'args': {'-avP': '', '--delete': '', '--exclude': '.*.swp'}, 'local_path': '/Users/goodlplus/Documents/code/python/PFA_BUPT/pfa/', 'remote_user': 'pris', 'remote_host': '10.112.232.233', 'remote_path': '/home/ljh/Documents/code/python/PFA/pfa/'},
"   \ {'args': {'-avP': '', '--delete': '', '--exclude': '.*.swp'}, 'local_path': '/Users/goodlplus/Documents/code/python/PFA_BUPT/pfa/', 'remote_user': 'pris', 'remote_host': '10.112.204.116', 'remote_path': '/home/ljh/Documents/code/python/PFA/pfa/'},
"   \ {'args': {'-avP': '', '--delete': '', '--exclude': '.*.swp'}, 'local_path': '/home/ljh/Documents/code/python/DeepFake_rPPG/', 'remote_user': 'ljh', 'remote_host': '10.112.71.173', 'remote_path': '~/Documents/code/python/DeepFake_rPPG/code/'},
